adv_analyzer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from advapp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('advapp/', include('advapp.urls')),
    path('', views.CreateUser, name = 'signup'),
    path('login/', views.Login, name = 'login'),
    path('signup/', views.CreateUser, name = 'signup'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

advapp/urls.py
from django.urls import path
from . import views

app_name = 'advapp'

urlpatterns = [
    path('main/<int:id>/<str:customer>', views.Main, name =  'main'),
    
    # Display All Ads
    path('display/<str:uname>', views.displayAds, name = 'display'),
    
    # When user clicks an ad, get the details of perticular ad
    path('detail/<str:uid>/<str:adid>', views.getAdDetails, name = 'detail'),
    
    # Manage You own ads
    path('manage/<int:id>', views.manageAds, name = 'manage'),
    path('create/<int:id>', views.AdCreate, name = 'create'),
]

advapp/models.py
from django.db import models
import os

# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    username = models.CharField(max_length=20, unique=True)
    email_id = models.EmailField()
    password = models.CharField(max_length = 20)
    customer = models.BooleanField()
    
    def __str__(self):
        return self.username
    
class UserResults(models.Model):
    username = models.ForeignKey('User', on_delete=models.SET_NULL, null=True)
    emotion_name = models.CharField(max_length=20)
    addId = models.ForeignKey('Advertisement', on_delete=models.SET_NULL, null=True)
    
def path_and_rename(instance, filename):
    upload_to = 'ads'
    ext = filename.split('.')[-1]
    if instance.addId:
        filename = '{}.{}'.format(instance.pk, ext)
    else:
        pass
    return os.path.join(upload_to, filename)

class Advertisement(models.Model):
    addId = models.CharField(max_length=30,primary_key = True)
    adDescription = models.CharField(max_length=600)
    adName = models.CharField(max_length=30)
    image = models.ImageField(upload_to = path_and_rename)
    username = models.ForeignKey('User', on_delete=models.SET_NULL, null=True)
    
    def __str__(self):
        return str(self.addId)

advapp/forms.py
from django import forms
from .models import *

class AdvertisementForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    class Meta:
        model = Advertisement
        fields = ['adName','addId','adDescription', 'image']
        labels  = {
        'addId':'',
        'adName': '',
        'adDescription' : '',
        'image':'Click here to upload advertisement', 
        }
        widgets = {
            'addId' : forms.TextInput(attrs={'placeholder':'Your unique advertisement ID here'}),
            'adName' : forms.TextInput(attrs={'placeholder':'Your advertisement name here'}),
            'adDescription' : forms.TextInput(attrs={'placeholder':'Your advertisement description here'}),
        }

advapp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .models import *
from django.urls import reverse
import cv2
from .machinelearning import pipeline_model
from .forms import AdvertisementForm

# Create your views here.

# REGISTER A USER
def CreateUser(request):
    if request.POST:
        # Get the values from HTML file
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email_id = request.POST['email_id']
        password = request.POST['password']
        # check if user is a customer or not
        if customer in request.POST:
            customer = True
        else:
            customer = False
        try:
            # Add user into database
            User.objects.create(first_name=first_name, last_name=last_name,username=username,email_id=email_id,password=password, customer=customer)
            return redirect(reverse('login'))
        except:
            # If we get any errors, then display to signup again.
            return render(request, 'signup.html', {'error': "User already exist or invalid details, please try again!"})
    return render(request, 'signup.html')

# Login Page
def Login(request):
    # Get the username and password to validate
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        try:
            # Check if user exist or not
            user = User.objects.get(username=username)
            if user.username == username and user.password == password:
                webpage = reverse('advapp:main', kwargs={'id':user.id, 'customer' : user.customer})
                return HttpResponseRedirect(webpage)
            else:
                # If user does not exist, then display an alert message
                return render(request, 'login.html', {'error' : "Invalid credentials, plesse login again"})
        except Exception as e:
            # If user does not exist, then display an error message
            return render(request, 'login.html', {'error' : "User does not exist, please signup again!"})
    return render(request, 'login.html')

# Display avalibale advertisements
def displayAds(request, uname):
    user = User.objects.get(username = uname)
    # get all the advertisements to send into template
    imgobj = Advertisement.objects.all()
    return render(request, 'displayAll.html', {'imgobj':imgobj, 'id' : user.id})

# When the user clicks a specific advertisement
def getAdDetails(request,uid, adid):
    ad = Advertisement.objects.get(addId = adid)
    # If form is submitted, then evaluate the facial expression
    if request.POST:
        cap = cv2.VideoCapture(0, cv2.CAP_DSHOW)
        ret, frame = cap.read()
        res = pipeline_model(frame)
        cv2.waitKey(0)
        cap.release()
        cv2.destroyAllWindows()
        # Save the results in database
        user = User.objects.get(id = uid)
        adid = Advertisement.objects.get(addId = ad.addId)
        obj = UserResults(username = user, addId = adid, emotion_name = res['emotion_name'])
        obj.save()
        return render(request, 'adDetail.html', {'ad': ad, 'detected' : "Your emotion has been recorded successfully, Thankyou!"})
    return render(request, 'adDetail.html', {'ad': ad, 'flag' : True})


# Main page
def Main(request, id, customer):
    obj = User.objects.get(id = id)
    if obj.customer == True:
        return render(request, 'main.html', {'id':obj.id, 'username':obj.username, 'name' : obj.first_name + ' ' + obj.last_name, 'customer' : customer})
    return render(request, 'main.html', {'id':obj.id, 'username':obj.username, 'name' : obj.first_name + ' ' + obj.last_name})


# Get the results of their ads for advertisements owners
def manageAds(request,id):
    ads = Advertisement.objects.filter(username = id).all()
    results = {}
    for i in ads:
        users = UserResults.objects.filter(addId = i.addId).all()
        # Initially setting all expressions to 1
        sad = 1
        happy = 1
        angry = 1
        neutral = 1
        for user in users:
            if user.emotion_name == "sad":
                sad += 1
            elif user.emotion_name == "angry":
                angry += 1
            elif user.emotion_name == "neutral":
                neutral += 1
            else:
                happy += 1
        sadPercent = round((sad/(sad + angry + neutral + happy)) * 100,2)
        angryPercent = round((angry/(sad + angry + neutral + happy)) * 100,2)
        neutralPercent = round((neutral/(sad + angry + neutral + happy)) * 100,2)
        happyPercent = round((happy/(sad + angry + neutral + happy)) * 100,2)
        results[i.addId] = {'image' : i.image,'adName' : i.adName, 'adDescription' : i.adDescription, 'adid' : i.addId, 'sadP' : sadPercent, 'angryP' : angryPercent, 'neutralP' : neutralPercent, 'happyP' : happyPercent}
    return render(request, 'manage.html', {'ads':ads, 'id':id, 'results' : results})


# Create an advertisement
def AdCreate(request, id):
    form = AdvertisementForm()
    if request.POST:
        form = AdvertisementForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            s = form.save(commit = True)
            user = User.objects.get(id = id)
            s.username = user
            s.save()
            # If created then redirect into manage.html file
            return redirect(reverse('advapp:manage', kwargs={'id':id}))
    return render(request, 'adCreate.html', {'form':form})

advapp/templates/adCreate.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Create Advertisement</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    <style>
        #create {
            font-size: 14px;
            background: #fff;
        }
        
        #create .create-newsletter {
            padding: 50px 0;
            background: #f3f5fa;
            text-align: center;
            font-size: 15px;
            color: #444444;
        }
        
        #create .create-newsletter h4 {
            font-size: 24px;
            margin: 0 0 20px 0;
            padding: 0;
            line-height: 1;
            font-weight: 600;
            color: #37517e;
        }
        
        input[type="file"] {
            display: none;
            padding-bottom: 2px;
        }
        
        .custom-file-upload {
            top: 0;
            right: 0;
            bottom: 0;
            border: 0;
            background: none;
            font-size: 18px;
            padding: 2px 20px;
            background: #47b2e4;
            color: #fff;
            transition: 0.3s;
            border-radius: 50px;
            box-shadow: 0px 2px 15px rgba(0, 0, 0, 0.1);
            padding-bottom: 2px;
        }
        
        #create .create-newsletter form input {
            border: 0;
            padding: 4px 8px;
            border-radius: 50px;
            width: calc(100% - 100px);
        }
        
        .formInputFile {
            border: 0;
            padding: 4px 8px;
            border-radius: 50px;
            width: calc(100% - 100px);
        }
        
        #create .create-newsletter form input[type=submit]:hover {
            background: #209dd8;
        }
        
        .custom-file-upload:hover {
            background: #209dd8;
            cursor: pointer;
        }
    </style>
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top ">
        <div class="container d-flex align-items-center">

            <h1 class="logo me-auto"><a href="">Create Advertisement</a></h1>

            <nav id="navbar" class="navbar">
                <ul>
                    <li><a class="getstarted scrollto" href="{% url 'login' %}">Log out</a></li>
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav>
            <!-- .navbar -->
        </div>
    </header>
    <!-- End Header -->

    <!-- ======= Hero Section ======= -->
    <section id="hero" class="d-flex align-items-center">

        <div class="container">
            <div class="row">
                <div class="col-lg-6 d-flex flex-column justify-content-center pt-4 pt-lg-0 order-2 order-lg-1" data-aos="fade-up" data-aos-delay="200">
                    <h1>Advertisement Analyzer</h1>
                    <h2>Publicise All You Want</h2>
                </div>
                <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="zoom-in" data-aos-delay="200">
                    <img src="{% static 'assets/img/mainimg.jpg' %}" class="img-fluid animated" alt="">
                </div>
            </div>
        </div>

    </section>

    <main id="main">


        <!-- ======= Skills Section ======= -->
        <section id="create">
            <div class="container" data-aos="fade-up">
                <div class="create-newsletter">
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-6">
                                <h4>Create Advertisement</h4>
                                <div>
                                    <form method="post" enctype="multipart/form-data">
                                        {% csrf_token %} {{form.as_p}}
                                        <input type="submit" value="Create Advertisement" class="custom-file-upload">
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
        </section>
        <!-- End Skills Section -->

    </main>
    <!-- End #main -->

    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="container footer-bottom clearfix">
            <div class="copyright">
                Developed and Designed by <a href="https://www.linkedin.com/in/darsigangothri06/" target="_blank">Gangothri Darsi</a>
            </div>
        </div>
    </footer>
    <!-- End Footer -->

    <div id="preloader"></div>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

advapp/templates/displayAll.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Available Advertisements</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">


</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top ">
        <div class="container d-flex align-items-center">

            <h1 class="logo me-auto"><a href="">Available Ads</a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

            <nav id="navbar" class="navbar">
                <ul>
                    <li><a class="getstarted scrollto" href="{% url 'login' %}">Log out</a></li>
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav>
            <!-- .navbar -->

        </div>
    </header>
    <!-- End Header -->

    <!-- ======= Hero Section ======= -->
    <section id="hero" class="d-flex align-items-center">

        <div class="container">
            <div class="row">
                <div class="col-lg-6 d-flex flex-column justify-content-center pt-4 pt-lg-0 order-2 order-lg-1" data-aos="fade-up" data-aos-delay="200">
                    <h1>Advertisement Analyzer</h1>
                    <h2>Advertise for A Better Crowd</h2>
                </div>
                <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="zoom-in" data-aos-delay="200">
                    <img src="{% static 'assets/img/mainimg.jpg' %}" class="img-fluid animated" alt="">
                </div>
            </div>
        </div>

    </section>
    <!-- End Hero -->

    <main id="main">
        <!-- ======= Services Section ======= -->
        <section id="services" class="services section-bg">
            <div class="container" data-aos="fade-up">

                <div class="section-title">
                    <h2>Available Advertisements</h2>
                </div>
                <div class="row">
                    {% for image in imgobj %}
                    <div class="col-xl-3 col-md-6 d-flex align-items-stretch" data-aos="zoom-in" data-aos-delay="100">
                        <div class="icon-box">
                            <h4><a href="{% url 'advapp:detail' id image.addId %}">{{image.adName}}</a></h4>
                            <p>{{image.adDescription}}</p>
                        </div>
                    </div>
                    {% if forloop.counter|divisibleby:4 %}
                    <p></p> {% endif %} {% endfor %}
                </div>
            </div>
        </section>
        <!-- End Services Section -->

    </main>
    <!-- End #main -->

    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="container footer-bottom clearfix">
            <div class="copyright">
                Developed and Designed by <a href="https://www.linkedin.com/in/darsigangothri06/" target="_blank">Gangothri Darsi</a>
            </div>
        </div>
    </footer>
    <!-- End Footer -->

    <div id="preloader"></div>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>


    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

advapp/templates/main.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Home Page</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">


</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top ">
        <div class="container d-flex align-items-center">

            <h1 class="logo me-auto"><a href="">Welcome, {{name}}</a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

            <nav id="navbar" class="navbar">
                <ul>
                    <li><a class="nav-link scrollto active" href="#hero">Home</a></li>
                    <li><a class="nav-link scrollto" href="#about">About</a></li>
                    <li><a class="nav-link scrollto" href="#services">Features</a></li>
                    <li><a class="getstarted scrollto" href="{% url 'login' %}">Log out</a></li>
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav>
            <!-- .navbar -->

        </div>
    </header>
    <!-- End Header -->

    <!-- ======= Hero Section ======= -->
    <section id="hero" class="d-flex align-items-center">

        <div class="container">
            <div class="row">
                <div class="col-lg-6 d-flex flex-column justify-content-center pt-4 pt-lg-0 order-2 order-lg-1" data-aos="fade-up" data-aos-delay="200">
                    <h1>Advertisement Analyzer</h1>
                    <h2>A Collection of Expressions</h2>
                    {% if customer %}
                    <div class="d-flex justify-content-center justify-content-lg-start">
                        <a href="{% url 'advapp:display' username %}" class="btn-get-started scrollto">Display Available Ads</a>
                    </div>
                    {% else %}
                    <div class="d-flex justify-content-center justify-content-lg-start">
                        <a href="{% url 'advapp:manage' id %}" class="btn-get-started scrollto">Manage My Ads</a> &nbsp; &nbsp;
                        <a href="{% url 'advapp:create' id %}" class="btn-get-started scrollto">Create an advertisement</a>
                    </div>
                    {% endif %}
                </div>
                <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="zoom-in" data-aos-delay="200">
                    <img src="{% static 'assets/img/mainimg.jpg' %}" class="img-fluid animated" alt="">
                </div>
            </div>
        </div>

    </section>
    <!-- End Hero -->

    <main id="main">


        <!-- ======= About Us Section ======= -->
        <section id="about" class="about">
            <div class="container" data-aos="fade-up">

                <div class="section-title">
                    <h2>About Advertisement Analyzer</h2>
                </div>

                <div class="row content">
                    <div class="col-lg-12">
                        <p align="center">
                            Allows the user to create new advertisements and also displays statistics collectively for all their ads.
                        </p>
                    </div>
                </div>

            </div>
        </section>
        <!-- End About Us Section -->


        <!-- ======= Services Section ======= -->
        <section id="services" class="services section-bg">
            <div class="container" data-aos="fade-up">

                <div class="section-title">
                    <h2>Features</h2>
                </div>

                <div class="row">
                    <div class="col-xl-3 col-md-6 d-flex align-items-stretch" data-aos="zoom-in" data-aos-delay="100">
                        <div class="icon-box">
                            <h4><a href="">Create New Ads</a></h4>
                            <p>Users can create new ads from the create section.</p>
                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 d-flex align-items-stretch mt-4 mt-md-0" data-aos="zoom-in" data-aos-delay="200">
                        <div class="icon-box">
                            <h4><a href="">Display Ads</a></h4>
                            <p>Users can view available ads from display section.</p>
                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 d-flex align-items-stretch mt-4 mt-xl-0" data-aos="zoom-in" data-aos-delay="300">
                        <div class="icon-box">
                            <h4><a href="">Reactions Collection</a></h4>
                            <p>Users reactions are collected through face recognition and are stored in database.</p>
                        </div>
                    </div>

                    <div class="col-xl-3 col-md-6 d-flex align-items-stretch mt-4 mt-xl-0" data-aos="zoom-in" data-aos-delay="400">
                        <div class="icon-box">
                            <h4><a href="">Display Statistics</a></h4>
                            <p>Users can see all the reactions for the ads through a dashboard displaying the percent for each reaction.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- End Services Section -->

        <!-- ======= Frequently Asked Questions Section ======= -->
        <section id="faq" class="faq section-bg">
            <div class="container" data-aos="fade-up">

                <div class="section-title">
                    <h2>Frequently Asked Questions</h2>
                </div>

                <div class="faq-list">
                    <ul>
                        <li data-aos="fade-up" data-aos-delay="100">
                            <i class="bx bx-help-circle icon-help"></i> <a data-bs-toggle="collapse" class="collapse" data-bs-target="#faq-list-1">How to use Advertisement Analyzer? <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
                            <div id="faq-list-1" class="collapse show" data-bs-parent=".faq-list">
                                <p>
                                    Advertisement Analyzer is very simple to use. After logging to your account, you can either create a new advertisement or view all the available advertisements. By clicking the button when you view an advertisement, your expression will be detected and
                                    stored in a database.
                                </p>
                            </div>
                        </li>

                        <li data-aos="fade-up" data-aos-delay="200">
                            <i class="bx bx-help-circle icon-help"></i> <a data-bs-toggle="collapse" data-bs-target="#faq-list-2" class="collapsed">What features does Advertisement Analyzer have? <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
                            <div id="faq-list-2" class="collapse" data-bs-parent=".faq-list">
                                <p>
                                    Currently Advertisement Analyzer supports Display/Manage/Detect/Results features. We are starving more to add many new exciting features for our users and enhance experience.
                                </p>
                            </div>
                        </li>

                        <li data-aos="fade-up" data-aos-delay="300">
                            <i class="bx bx-help-circle icon-help"></i> <a data-bs-toggle="collapse" data-bs-target="#faq-list-3" class="collapsed">Is Advertisement Analyzer free and safe? <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
                            <div id="faq-list-3" class="collapse" data-bs-parent=".faq-list">
                                <p>
                                    Yes Advertisement Analyzer is free as well as safe for all the users. Your personal information is never shared with anyone, also the emotion at the time of detection is secured and safe.
                                </p>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </section>
        <!-- End Frequently Asked Questions Section -->

    </main>
    <!-- End #main -->

    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="container footer-bottom clearfix">
            <div class="copyright">
                Developed and Designed by <a href="https://www.linkedin.com/in/darsigangothri06/" target="_blank">Gangothri Darsi</a>
            </div>
        </div>
    </footer>
    <!-- End Footer -->

    <div id="preloader"></div>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>


    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>